version: '2'

services:
  main:
    build: .
    image: keep-alive-e5:latest
    container_name: keep-alive-e5
    environment:
      DOCKER: "true"
      # https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines
      USER: |-
        A@xx.onmicrosoft.com
        B@xx.onmicrosoft.com
      PASSWD: |-
        A_password
        B_password
